name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # يقبل رخص الـ Android SDK ويتأكد أن الـ SDK جاهز
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # إذا لم يكن لديك gradlew داخل الريبو، سننشئ الـ Wrapper مؤقتاً بهذه الخطوة
      - name: Generate Gradle Wrapper (if missing)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2
          arguments: wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: huawei-wifi-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
